# Server configurations
server:
  port: 8080
  host: localhost
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1048576

# Database configurations
database:
  driver: sqlite3
  dsn: gAgent.db

# Logging configurations
logging:
  level: info
  format: json
  output: stdout